version: "3"
services:
  frontend:
    image: ghcr.io/punthanat/int365-front-test2:master
    container_name: frontend
    ports:
      - "8080:80"
    networks:
       my_network:
          ipv4_address: 172.22.0.3
networks:
  default:
    external:
       name: my_network
  my_network:
    external: true